### ISSUE TITLE
Enhancements from the old roadmap

### ISSUE THREAD

**Issue by gggeek** [gggeek/jsxmlrpc#6]
- [ ] implement the function xmlrpc_decode_xml()
- [ ] handling of charset encoding (where explicitly requested)
- [ ] timeout in send() methods | OK only for async calls
- [x] async send() method
- [ ] compression of requests
- [ ] handling of compression, chunked encoding in parseResponseHeaders
- [ ] Testsuite, speed tests, demo files
- [ ] htmlentities only encodes as much as php function htmlspecialchars
- [ ] encoding/decoding of anon js classes via an xml attribute (since  it is hard to recover a class name, we could encode instead all methods code)
- [ ] complete parsing of: new xmlrpcclient('http://james:bond@a.complete/uri')
- [ ] using client credentials for https auth
